baseURL = 'https://jpscardoso97.github.io/'
languageCode = 'en-us'
title = 'João Cardoso | Software Engineer'
theme = 'minimal-portfolio'

[params]
  author = 'João Cardoso'
  description = 'Software Engineer | Duke University Masters in Artificial Intelligence'
  github = 'https://github.com/jpscardoso97'
  linkedin = 'https://www.linkedin.com/in/joaopsc/'
  instagram = 'https://instagram.com/k4rd050'
  email = 'jocardoso55@gmail.com'
  enableDarkMode = true
  defaultTheme = 'light'

[menu]
  [[menu.main]]
    name = 'About'
    url = '#about'
    weight = 1
  [[menu.main]]
    name = 'Experience'
    url = '#experience'
    weight = 2
  [[menu.main]]
    name = 'Education'
    url = '#education'
    weight = 3
  [[menu.main]]
    name = 'Projects'
    url = '#projects'
    weight = 4
